#! /usr/bin/env python

import click 


logger = logging.getLogger(__name__)

import logging
import os
import shutil
from pathlib import Path
from lesson_builder.util import find_file_path
import yaml
from textwrap import dedent
import click
from plumbum import local, FG
from plumbum.cmd import yarn, git
from plumbum.commands.processes import ProcessExecutionError
from slugify import slugify
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler